version: '3.4'

services:
  reactwebpack:
    image: reactwebpack
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run serve
    ports:
      - 3000:3000
    tty: true
    
