version: '3.4'

services:
  reactwebpack:
    image: reactwebpack
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /usr/share/nginx/html/index.html
    ports:
      - 3000:80
    tty: true
    
